/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Job: {
            /** @example job_123 */
            id: string;
            /** @example Senior Software Engineer */
            title: string;
            /** @example Tech Corp */
            company: string;
            /** @example San Francisco, CA */
            location?: string | null;
            /** @example true */
            isRemote: boolean;
            /** @example Full-time software engineering role... */
            description?: string | null;
            /**
             * Format: uri
             * @example https://jobs.example.com/123
             */
            applyUrl: string;
            /** @example $120k - $180k */
            salary?: string | null;
            /** Format: date-time */
            postedDate?: string | null;
            /** @example LinkedIn */
            source: string;
            /** @example 0.85 */
            relevanceScore?: number | null;
            /** @example true */
            processed: boolean;
            /** Format: date-time */
            createdAt: string;
            /** @example Jan 15, 2024 */
            formattedPostedDate?: string | null;
            /** @example Jan 15, 2024 */
            formattedCreatedAt: string;
            /** @example 85 */
            relevancePercentage: number;
            /**
             * @example default
             * @enum {string}
             */
            relevanceBadgeVariant: "default" | "secondary";
        };
        User: {
            /** @example 1 */
            id: number;
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example 12345678901234567890 */
            googleId: string;
            /** @example John Doe */
            name?: string | null;
            /** Format: uri */
            avatarUrl?: string | null;
            /** @example false */
            isAdmin: boolean;
            /** @example {
             *       "emailNotifications": true,
             *       "theme": "light"
             *     } */
            settings: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        JobStage: {
            /** @example 1 */
            id: number;
            /** @example null */
            userId?: number | null;
            /** @example Interested */
            name: string;
            /** @example #3B82F6 */
            color: string;
            /** @example 1 */
            sortOrder: number;
            /** @example true */
            isSystem: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        UserJob: {
            /** @example 1 */
            id: number;
            /** @example 1 */
            userId: number;
            /** @example job_123 */
            jobId: string;
            /** @example 1 */
            stageId: number;
            /** @example true */
            isTracked: boolean;
            /** Format: date-time */
            appliedDate?: string | null;
            /** Format: date-time */
            interviewDate?: string | null;
            /** @example Looks promising, matches my skills */
            notes?: string | null;
            /** Format: uri */
            applicationUrl?: string | null;
            /** @example Jane Smith */
            contactPerson?: string | null;
            /** @example 150000 */
            salaryExpectation?: number | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ApiResponse: {
            /** @example true */
            success: boolean;
            data?: Record<string, never> | null;
            error?: string | null;
            message?: string | null;
        };
        PaginationMeta: {
            /** @example 150 */
            total: number;
            /** @example 20 */
            limit: number;
            /** @example 0 */
            offset: number;
            /** @example 20 */
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
