// This file will be auto-generated by openapi-typescript
// Run: npm run generate-api-types to generate types from OpenAPI spec

// Placeholder types until generation
export interface Job {
  id: number;
  title: string;
  company: string;
  location?: string;
  description?: string;
  relevanceScore: number;
  url?: string;
  source?: string;
  postedDate?: string;
  salary?: string;
  remote?: boolean;
  processed: boolean;
  archived: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface User {
  id: number;
  email: string;
  googleId: string;
  name?: string;
  avatarUrl?: string;
  isAdmin: boolean;
  settings: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}

export interface JobStage {
  id: number;
  userId?: number;
  name: string;
  color: string;
  sortOrder: number;
  isSystem: boolean;
  createdAt: string;
}

export interface UserJob {
  id: number;
  userId: number;
  jobId: number;
  stageId: number;
  isTracked: boolean;
  appliedDate?: string;
  interviewDate?: string;
  notes?: string;
  applicationUrl?: string;
  contactPerson?: string;
  salaryExpectation?: number;
  createdAt: string;
  updatedAt: string;
}