[build]
builder = "nixpacks"
buildCommand = "npx nx build api"

[deploy]
startCommand = "start:api"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"