[build]
builder = "nixpacks"
buildCommand = "npm run build:web"

[deploy]
startCommand = "npm run start:web"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"